name: Node.js Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 16
 # [Fitbit SDK CLI Example Build/ Install Fitbit OS Apps.](https://gist.github.com/princessleia1/2a0b2d9f5f8438a4ee0050d16d86ab0a)
      - run: sudo apt-get install libsecret-1-dev
      
      - run: npm install
      
      - run: npm run-script build
      
      - run: ls
